name: 02 - Workflow Events
run-name: ${{ github.event_name != 'schedule' && 'Build and Test' || 'daily-build' }}
on: 
    workflow_dispatch:
    schedule:
        - cron: '*/2 * * * *' # Every 2 minutes
 
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "I've been triggered by a(n) ${{ github.event_name }} event."


