name: 02 - Workflow Events
run-name: ${{ github.event_name == 'schedule' && 'daily-build' || github.workflow }}
on: 
    workflow_dispatch:
    #schedule:
    #    - cron: '*/1 * * * *' # Every 1 minutes
 
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "I've been triggered by a(n) ${{ github.event_name }} event."


