name: 12 - Working with Outputs
on: 
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                options: ['success', 'failure']
                default: 'success'
                description: 'Status of the build'

env:
    myVar: "Hello from env"
            
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ steps.build.outputs.status }}
        steps:
            - name: Print GITHUB_OUTPUT path
              run: echo "$GITHUB_OUTPUT"
            - name: SetEnv
              run: echo "myVar=Hello from step" >> $GITHUB_ENV
            - name: Build
              id: build
              run: |
                echo "$GITHUB_OUTPUT"  
                echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
                echo "output1=value1" >> "$GITHUB_OUTPUT"
                echo "output2=value2" >> "$GITHUB_OUTPUT"
                echo "env=$myVar" >> "$GITHUB_OUTPUT"
                cat "$GITHUB_OUTPUT"
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ needs.build.outputs.build-status == 'success' }}
        steps:
            - name: Deploy
              run: echo "Deploying"
    echo-test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Echo test
              run: |
                echo "Output from build job"
                echo "Build Status: ${{ needs.build.outputs.build-status }}"
                echo "Output1: ${{ needs.build.outputs.output1 }}"
                echo "Output2: ${{ needs.build.outputs.output2 }}"
