name: 15 - Working with Matrices

on:
  workflow_dispatch:

jobs:
  backwards-compatibility:
    name: ${{ matrix.os }}-${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        node-version: [18.x, 20.x, 21.x]
        os:
        - ubuntu-latest
        - windows-latest
        include:
          - os: ubuntu-latest
            node-version: 16.x
          - os: ubuntu-latest
            node-version: 21.x
            tag: experimental
    steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with: 
        node-version: ${{ matrix.node-version }}
    - name: Fail if experimental
      if: matrix.tag == 'experimental'
      run: exit 1
    - name: Perform some tests
      run: |
        echo "Running tests on OS ${{ matrix.os }} with NodeJS ${{ matrix.node-version }}-${{ matrix.opacity}}"
        sleep 10
    - name: Upload test results
      run: echo "Test results uploaded"
  include-example:
    name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        color: [red, green]
        shape: [circle, square]
        size: [small, large]
        include: 
          - opacity: 50
          - color: red
            shape: triangle
    steps:
    - name: Dummy step
      run: echo "${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}"
      
