name: 17 - 3 - Custom Actions - Docker
run-name: 17 - 2 - Custom Actions - JS | BB - ${{ inputs.base-branch }}  TB - ${{ inputs.target-branch }} WD - ${{ inputs.working-dir }}
on:
  workflow_dispatch:
    inputs:
      url:
        type: string
        default: 'https://www.google.com  '

permissions: 
  contents: write
  pull-requests: write

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
